name: First Workflow
on: push
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node.js dependencies
        run: npm ci
      - name: es lint dependencies
        run: npm init @eslint/config
      - name: lint
        run: npm run lint
  test-job:
    needs: lint-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Node.js dependencies
        run: npm ci
      - name: test
        run: npm run test
  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Node.js dependencies
        run: npm ci
      - name: build
        run: npm run build
