name: First Workflow
on: workflow_dispatch
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
      - name: lint
        run: npm lint
  test-job:
    needs: lint-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
      - name: lint
        run: npm test
  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
      - name: lint
        run: npm build
