name: First Workflow
on: push
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
      - name: Node.js dependencies
        run: npm ci
      - name: lint
        run: npm run lint
  test-job:
    needs: lint-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
      - name: Node.js dependencies
        run: npm ci
      - name: lint
        run: npm run test
  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
      - name: Node.js dependencies
        run: npm ci
      - name: lint
        run: npm run build
