name: issues details
on: issues
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Checkout
        uses: echo "${{ github.event }}
